// Ghost roster
const GHOSTS = [
  { id: 'aswang', name: 'Aswang' },
  { id: 'banshee', name: 'Banshee' },
  { id: 'demon', name: 'Demon' },
  { id: 'doppelganger', name: 'Doppelganger' },
  { id: 'dullahan', name: 'Dullahan' },
  { id: 'dybbuk', name: 'Dybbuk' },
  { id: 'entity', name: 'Entity' },
  { id: 'ghoul', name: 'Ghoul' },
  { id: 'keres', name: 'Keres' },
  { id: 'leviathan', name: 'Leviathan' },
  { id: 'nightmare', name: 'Nightmare' },
  { id: 'oni', name: 'Oni' },
  { id: 'phantom', name: 'Phantom' },
  { id: 'ravager', name: 'Ravager' },
  { id: 'revenant', name: 'Revenant' },
  { id: 'shadow', name: 'Shadow' },
  { id: 'siren', name: 'Siren' },
  { id: 'specter', name: 'Specter' },
  { id: 'spirit', name: 'Spirit' },
  { id: 'umbra', name: 'Umbra' },
  { id: 'vesper', name: 'Vesper' },
  { id: 'vex', name: 'Vex' },
  { id: 'the-wisp', name: 'The Wisp' },
  { id: 'wraith', name: 'Wraith' },
  { id: 'wretch', name: 'Wretch' },
];

// Evidence roster.
// type "positive": observing this evidence CONFIRMS the ghost must be one of `ghosts`.
// type "negative": observing this evidence RULES OUT the ghost(s) in `ghosts`.
const EVIDENCE = [
  // Movement
  { id: 'm1', category: 'Movement', text: 'Speed increases after every kill', type: 'positive', ghosts: ['aswang'] },
  { id: 'm2', category: 'Movement', text: 'Sprints during the hunt', type: 'positive', ghosts: ['oni'] },
  { id: 'm3', category: 'Movement', text: 'Speed decreases after every kill', type: 'positive', ghosts: ['keres'] },
  { id: 'm4', category: 'Movement', text: 'Moves faster when invisible during the hunt', type: 'positive', ghosts: ['phantom'] },
  { id: 'm5', category: 'Movement', text: 'Moves faster the longer it sees the target', type: 'positive', ghosts: ['dullahan'] },
  { id: 'm6', category: 'Movement', text: 'Teleports', type: 'positive', ghosts: ['entity'] },
  { id: 'm7', category: 'Movement', text: 'Stands still when not hunting', type: 'positive', ghosts: ['specter'] },
  { id: 'm8', category: 'Movement', text: 'Speed increases if average energy level is below 50%', type: 'positive', ghosts: ['wretch'] },
  { id: 'm9', category: 'Movement', text: 'Speed decreases in the warm room', type: 'positive', ghosts: ['umbra'] },

  // Hunting Frequency
  { id: 'h1', category: 'Hunting Frequency', text: 'Hunts frequently', type: 'positive', ghosts: ['demon'] },
  { id: 'h2', category: 'Hunting Frequency', text: 'Hunts more frequently in the dark', type: 'positive', ghosts: ['nightmare'] },

  // Other Signs
  { id: 'o1', category: 'Other Signs', text: 'Appears headless in photos', type: 'positive', ghosts: ['dullahan'] },
  { id: 'o2', category: 'Other Signs', text: 'Footprint in salt', type: 'negative', ghosts: ['wraith'] },
  { id: 'o3', category: 'Other Signs', text: 'Lifts the cross during the hunt', type: 'positive', ghosts: ['demon'] },
  { id: 'o4', category: 'Other Signs', text: 'Alters flame color', type: 'positive', ghosts: ['spirit'] },
  { id: 'o5', category: 'Other Signs', text: 'Starts candle fires', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'o6', category: 'Other Signs', text: 'Passes through walls', type: 'positive', ghosts: ['vex'] },
  { id: 'o7', category: 'Other Signs', text: 'Does not kill while standing still', type: 'positive', ghosts: ['vesper'] },
  { id: 'o8', category: 'Other Signs', text: 'Switches on electronics during the hunt', type: 'negative', ghosts: ['ghoul'] },
  { id: 'o9', category: 'Other Signs', text: 'Starts a hunt after spamming the spirit box', type: 'positive', ghosts: ['ghoul'] },
  { id: 'o10', category: 'Other Signs', text: 'Teleports things', type: 'positive', ghosts: ['entity'] },
  { id: 'o11', category: 'Other Signs', text: 'Throws corpses after killing', type: 'positive', ghosts: ['dybbuk'] },
  { id: 'o12', category: 'Other Signs', text: 'Blinks consistently', type: 'positive', ghosts: ['phantom'] },
  { id: 'o13', category: 'Other Signs', text: 'Humming in the spirit box', type: 'positive', ghosts: ['siren'] },
  { id: 'o14', category: 'Other Signs', text: 'Things vortex', type: 'positive', ghosts: ['ravager'] },
  { id: 'o15', category: 'Other Signs', text: 'Big delays between throwing items', type: 'positive', ghosts: ['entity'] },
  { id: 'o16', category: 'Other Signs', text: 'Distinct banshee wail', type: 'positive', ghosts: ['banshee'] },
  { id: 'o17', category: 'Other Signs', text: 'Footsteps sound', type: 'negative', ghosts: ['umbra'] },
  { id: 'o18', category: 'Other Signs', text: 'Starts the hunt near a lit flame', type: 'negative', ghosts: ['wretch'] },
  { id: 'o19', category: 'Other Signs', text: 'Starts a hunt only in its favorite room', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'o20', category: 'Other Signs', text: 'Fakes a ghost orb', type: 'positive', ghosts: ['doppelganger'] },
  { id: 'o21', category: 'Other Signs', text: 'Mimics other ghosts’ abilities', type: 'positive', ghosts: ['doppelganger'] },
  { id: 'o22', category: 'Other Signs', text: 'Leaves EMF level 5', type: 'positive', ghosts: ['ravager'] },
  { id: 'o23', category: 'Other Signs', text: 'Temperature changes between 0.04–0.08℃', type: 'positive', ghosts: ['shadow'] },
  { id: 'o24', category: 'Other Signs', text: 'Male voice in the spirit box', type: 'negative', ghosts: ['keres', 'siren'] },
  { id: 'o25', category: 'Other Signs', text: 'Disables lights outside of hunts', type: 'positive', ghosts: ['leviathan'] },
  { id: 'o26', category: 'Other Signs', text: 'Gets stunned for 3 seconds while the music box is played', type: 'positive', ghosts: ['dybbuk'] },
  { id: 'o27', category: 'Other Signs', text: 'Targets hunters with the lowest energy level', type: 'positive', ghosts: ['keres'] },
  { id: 'o28', category: 'Other Signs', text: 'Hunt stops after a kill', type: 'positive', ghosts: ['revenant'] },
  { id: 'o29', category: 'Other Signs', text: 'Can walk through fire', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'o30', category: 'Other Signs', text: 'Invisible on LIDAR scans', type: 'positive', ghosts: ['vex'] },
  { id: 'o31', category: 'Other Signs', text: 'Sound hallucinations', type: 'positive', ghosts: ['nightmare'] },
];
