// Ghost roster
const GHOSTS = [
  { id: 'aswang', name: 'Aswang' },
  { id: 'banshee', name: 'Banshee' },
  { id: 'demon', name: 'Demon' },
  { id: 'doppelganger', name: 'Doppelganger' },
  { id: 'dullahan', name: 'Dullahan' },
  { id: 'dybbuk', name: 'Dybbuk' },
  { id: 'entity', name: 'Entity' },
  { id: 'ghoul', name: 'Ghoul' },
  { id: 'keres', name: 'Keres' },
  { id: 'leviathan', name: 'Leviathan' },
  { id: 'nightmare', name: 'Nightmare' },
  { id: 'oni', name: 'Oni' },
  { id: 'phantom', name: 'Phantom' },
  { id: 'ravager', name: 'Ravager' },
  { id: 'revenant', name: 'Revenant' },
  { id: 'shadow', name: 'Shadow' },
  { id: 'siren', name: 'Siren' },
  { id: 'specter', name: 'Specter' },
  { id: 'spirit', name: 'Spirit' },
  { id: 'umbra', name: 'Umbra' },
  { id: 'vesper', name: 'Vesper' },
  { id: 'vex', name: 'Vex' },
  { id: 'the-wisp', name: 'The Wisp' },
  { id: 'wraith', name: 'Wraith' },
  { id: 'wretch', name: 'Wretch' },
];

// Evidence roster.
// type "positive": observing this evidence TRUE confirms the ghost must be one of `ghosts`.
// type "negative": observing this evidence TRUE rules out the ghost(s) in `ghosts`.
const EVIDENCE = [
  // Movement
  { id: 'w1', category: 'Movement', text: 'Speed increases after every kill', type: 'positive', ghosts: ['aswang'] },
  { id: 'w2', category: 'Movement', text: 'Sprints during the hunt', type: 'positive', ghosts: ['oni'] },
  { id: 'w3', category: 'Movement', text: 'Speed decreases after every kill', type: 'positive', ghosts: ['keres'] },
  { id: 'w4', category: 'Movement', text: 'Moves faster when invisible during the hunt', type: 'positive', ghosts: ['phantom'] },
  { id: 'w5', category: 'Movement', text: 'Moves faster the longer it sees the target', type: 'positive', ghosts: ['dullahan'] },
  { id: 'w6', category: 'Movement', text: 'Teleports', type: 'positive', ghosts: ['entity'] },
  { id: 'w7', category: 'Movement', text: 'Stands still when not hunting', type: 'positive', ghosts: ['specter'] },
  { id: 'w8', category: 'Movement', text: 'Speed increases if average energy level is below 50%', type: 'positive', ghosts: ['wretch'] },
  { id: 'w9', category: 'Movement', text: 'Speed decreases in the warm room', type: 'positive', ghosts: ['umbra'] },
  { id: 'w10', category: 'Movement', text: 'Can walk through fire', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'w11', category: 'Movement', text: 'Passes through walls', type: 'positive', ghosts: ['vex'] },
  { id: 'w12', category: 'Movement', text: 'Footsteps sound', type: 'negative', ghosts: ['umbra'] },

  // Hunting
  { id: 'h1', category: 'Hunting', text: 'Hunts frequently', type: 'positive', ghosts: ['demon'] },
  { id: 'h2', category: 'Hunting', text: 'Hunts more frequently in the dark', type: 'positive', ghosts: ['nightmare'] },
  { id: 'h3', category: 'Hunting', text: 'Does not kill while standing still', type: 'positive', ghosts: ['vesper'] },
  { id: 'h4', category: 'Hunting', text: 'Hunt stops after a kill', type: 'positive', ghosts: ['revenant'] },
  { id: 'h5', category: 'Hunting', text: 'Targets hunters with the lowest energy level', type: 'positive', ghosts: ['keres'] },
  { id: 'h6', category: 'Hunting', text: 'Starts a hunt only in its favorite room', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'h7', category: 'Hunting', text: 'Appears headless in photos', type: 'positive', ghosts: ['dullahan'] },
  { id: 'h8', category: 'Hunting', text: 'Lifts the cross during the hunt', type: 'positive', ghosts: ['demon'] },
  { id: 'h9', category: 'Hunting', text: 'Switches on electronics during the hunt', type: 'negative', ghosts: ['ghoul'] },
  { id: 'h10', category: 'Hunting', text: 'Male skin', type: 'negative', ghosts: ['siren', 'keres'] },
  { id: 'h11', category: 'Hunting', text: 'Starts the hunt near a lit flame', type: 'negative', ghosts: ['wretch'] },
  { id: 'h12', category: 'Hunting', text: 'Alters flame color', type: 'positive', ghosts: ['spirit'] },
  { id: 'h13', category: 'Hunting', text: 'Starts a hunt after spamming the spirit box', type: 'positive', ghosts: ['ghoul'] },
  { id: 'h14', category: 'Hunting', text: 'Blinks consistently', type: 'positive', ghosts: ['phantom'] },
  { id: 'h15', category: 'Hunting', text: 'Things vortex', type: 'positive', ghosts: ['ravager'] },
  { id: 'h16', category: 'Hunting', text: 'Big delays between throwing items', type: 'positive', ghosts: ['entity'] },
  { id: 'h17', category: 'Hunting', text: 'Distinct banshee wail', type: 'positive', ghosts: ['banshee'] },

  // Not Hunting
  { id: 'n1', category: 'Not Hunting', text: 'Footprint in salt', type: 'negative', ghosts: ['wraith'] },
  { id: 'n2', category: 'Not Hunting', text: 'Starts candle fires', type: 'positive', ghosts: ['the-wisp'] },
  { id: 'n3', category: 'Not Hunting', text: 'Teleports things', type: 'positive', ghosts: ['entity'] },
  { id: 'n4', category: 'Not Hunting', text: 'Throws corpses after killing', type: 'positive', ghosts: ['dybbuk'] },
  { id: 'n5', category: 'Not Hunting', text: 'Humming in the spirit box', type: 'positive', ghosts: ['siren'] },
  { id: 'n6', category: 'Not Hunting', text: 'Ghost orb visible', type: 'positive', ghosts: ['doppelganger'] },
  { id: 'n7', category: 'Not Hunting', text: 'Mimics other ghosts’ abilities', type: 'positive', ghosts: ['doppelganger'] },
  { id: 'n8', category: 'Not Hunting', text: 'Leaves EMF level 5', type: 'positive', ghosts: ['ravager'] },
  { id: 'n9', category: 'Not Hunting', text: 'Temperature between 0.04–0.08℃', type: 'positive', ghosts: ['shadow'] },
  { id: 'n10', category: 'Not Hunting', text: 'Female voice in the spirit box', type: 'positive', ghosts: ['keres', 'siren'] },
  { id: 'n11', category: 'Not Hunting', text: 'Disables lights outside of hunts', type: 'positive', ghosts: ['leviathan'] },
  { id: 'n12', category: 'Not Hunting', text: 'Gets stunned for 3 seconds while the music box is played', type: 'positive', ghosts: ['dybbuk'] },
  { id: 'n13', category: 'Not Hunting', text: 'Visible on LIDAR scans', type: 'negative', ghosts: ['vex'] },
  { id: 'n14', category: 'Not Hunting', text: 'Sound hallucinations', type: 'positive', ghosts: ['nightmare'] },
];
